[package]
name = "tauri"
version = "0.12.0"
authors = [
  "Lucas Fernandes Gonçalves Nogueira <lucas@tauri.studio>",
  "Daniel Thompson-Yvetot <denjell@sfosc.org>",
  "Tensor Programming <tensordeveloper@gmail.com>"
]
categories = [ "gui", "web-programming" ]
license = "MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Make tiny, secure apps for all desktop platforms with Tauri"
edition = "2018"
exclude = [ "test/fixture/**" ]

[package.metadata.docs.rs]
features = [ "all-api" ]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
base64 = "0.13.0"
webbrowser = "0.5.5"
lazy_static = "1.4.0"
tiny_http = { version = "0.8", optional = true }
tokio = { version = "1.2", features = [ "rt", "rt-multi-thread", "sync" ] }
futures = "0.3"
async-trait = "0.1"
uuid = { version = "0.8.2", features = [ "v4" ] }
thiserror = "1.0.23"
once_cell = "1.5.2"
tauri-api = { version = "0.8.0", path = "../tauri-api" }
tauri-macros = { version = "0.2", path = "../tauri-macros" }
wry = { git = "https://github.com/tauri-apps/wry", rev = "f4edf89de5dc40b77a94f6b94fcaf76fdac6bbf4" }

[target."cfg(target_os = \"windows\")".dependencies]
runas = "0.2"

[build-dependencies]
cfg_aliases = "0.1.1"

[dev-dependencies]
proptest = "0.10.1"
serde_json = "1.0"
tauri = { path = ".", features = [ "all-api" ] }
serde = { version = "1.0", features = [ "derive" ] }

[features]
cli = [ "tauri-api/cli" ]
embedded-server = [ "tiny_http" ]
all-api = [ "tauri-api/notification" ]
read-text-file = [ ]
read-binary-file = [ ]
write-file = [ ]
write-binary-file = [ ]
read-dir = [ ]
copy-file = [ ]
create-dir = [ ]
remove-dir = [ ]
remove-file = [ ]
rename-file = [ ]
path-api = [ ]
set-title = [ ]
execute = [ ]
open = [ ]
event = [ ]
updater = [ ]
open-dialog = [ ]
save-dialog = [ ]
http-request = [ ]
notification = [ "tauri-api/notification" ]

[[example]]
name = "communication"
path = "examples/communication/src-tauri/src/main.rs"

[[example]]
name = "multiwindow"
path = "examples/multiwindow/src-tauri/src/main.rs"
