[package]
name = "tauri-macros"
version = "0.2.0"
authors = [ "Tauri Community" ]
categories = [ "gui", "os", "filesystem", "web-programming" ]
license = "MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Macros for the tauri crate."
edition = "2018"

[lib]
proc-macro = true

[dependencies]
flate2 = "1"
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
syn = { version = "1", features = [ "extra-traits" ] }
tauri-utils = { version = "0.6", path = "../tauri-utils" }
walkdir = "2"
